version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: framings-db
    environment:
      POSTGRES_USER: ${DB_USER:-framings}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      POSTGRES_DB: ${DB_NAME:-framings-law}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: "Asia/Tokyo"
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"

volumes:
  db-data:
