version: "3.8"

services:
  db:
    image: postgres:14-alpine
    container_name: framings-db
    environment:
      POSTGRES_USER: ${DB_USER:-framings}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-p@ssw0rd}
      POSTGRES_DB: ${DB_NAME:-framings-law}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      TZ: "Asia/Tokyo"
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - "db-data:/var/lib/postgresql/data"
  migration:
    image: flyway/flyway
    volumes:
      - ./database/migration/schema:/flyway/sql
    depends_on:
      - db
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: framings-swagger
    environment:
      - SWAGGER_URL=./swagger.yaml
      - SWAGGER_JSON=/swagger/swagger.yaml
    ports:
      - 8080:8080
    volumes:
      - ./swagger/:/swagger
volumes:
  db-data:
