/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/users/{userId}": {
    /**
     * Get User Info by User ID 
     * @description Retrieve the information of the user with the matching user ID.
     */
    get: operations["get-users-userId"];
    /**
     * Update User Information 
     * @description Update the information of an existing user.
     */
    patch: operations["patch-users-userId"];
    parameters: {
        /** @description Id of an existing user. */
      path: {
        userId: string;
      };
    };
  };
  "/user": {
    /**
     * Create New User 
     * @description Create a new user.
     */
    post: operations["post-user"];
  };
  "/rooms/{roomId}/join": {
    /** ルームに参加 */
    post: operations["post-rooms-roomId-join"];
    parameters: {
      path: {
        roomId: string;
      };
    };
  };
  "/rooms/": {
    /**
     * ルームの作成 
     * @description 新しくゲームのルームを作成する。
     */
    post: operations["post-rooms"];
  };
  "/games/{gameId}": {
    /**
     * 特定のゲームの状態を取得する 
     * @description {gameId}で指定されたゲームの状態を取得する。
     */
    get: operations["get-games-gameId"];
    parameters: {
      path: {
        gameId: string;
      };
    };
  };
  "/games/{gameId}/posts": {
    /**
     * ゲーム内の投稿一覧取得 
     * @description {gameId}で指定されたゲーム内の投稿を一覧取得する。
     * 削除された投稿は除外して取得する。
     */
    get: operations["get-games-gameId-posts"];
    parameters: {
      path: {
        gameId: string;
      };
    };
  };
}

export type webhooks = Record<string, never>;

export type components = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  "get-users-userId": {
    /**
     * Get User Info by User ID 
     * @description Retrieve the information of the user with the matching user ID.
     */
    responses: {
      /** @description User Found */
      200: never;
      /** @description User Not Found */
      404: never;
    };
  };
  "patch-users-userId": {
    /**
     * Update User Information 
     * @description Update the information of an existing user.
     */
    responses: {
      /** @description User Updated */
      200: never;
      /** @description User Not Found */
      404: never;
      /** @description Email Already Taken */
      409: never;
    };
  };
  "post-user": {
    /**
     * Create New User 
     * @description Create a new user.
     */
    responses: {
      /** @description User Created */
      200: never;
      /** @description Missing Required Information */
      400: never;
      /** @description Email Already Taken */
      409: never;
    };
  };
  "post-rooms-roomId-join": {
    /** ルームに参加 */
    parameters?: {
      header?: {
        undefined?: string;
      };
    };
    responses: {
      /** @description OK */
      200: never;
    };
  };
  "post-rooms": {
    /**
     * ルームの作成 
     * @description 新しくゲームのルームを作成する。
     */
    responses: {
      /** @description OK */
      200: never;
    };
  };
  "get-games-gameId": {
    /**
     * 特定のゲームの状態を取得する 
     * @description {gameId}で指定されたゲームの状態を取得する。
     */
    responses: {
    };
  };
  "get-games-gameId-posts": {
    /**
     * ゲーム内の投稿一覧取得 
     * @description {gameId}で指定されたゲーム内の投稿を一覧取得する。
     * 削除された投稿は除外して取得する。
     */
    responses: {
    };
  };
}
