export const FIREBASE = {
  API_KEY: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  AUTH_DOMAIN: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
  PROJECT_ID: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
  APP_ID: process.env.NEXT_PUBLIC_FIREBASE_APP_ID
}

export const PUSHER = {
  APP_ID: process.env.NEXT_PUBLIC_PUSHER_APP_ID as string,
  APP_KEY: process.env.NEXT_PUBLIC_PUSHER_APP_KEY as string,
  APP_SECRET: process.env.NEXT_PUBLIC_PUSHER_APP_SECRET as string
}
